/**
 * French translations, keyed by the string used in data-i18n / data-i18n-html
 * / data-i18n-placeholder / data-i18n-aria attributes across the site.
 * English is read directly from the HTML — it never needs to be duplicated here.
 */
window.FR_DICT = {
  /* ---------- Header / Nav ---------- */
  "nav.tagline": "Tours & Safari",
  "nav.home": "Accueil",
  "nav.about": "Emanueli",
  "nav.destinations": "Destinations",
  "nav.tours": "Safaris & Tarifs",
  "nav.gallery": "Galerie",
  "nav.faq": "FAQ",
  "nav.contact": "Contact",
  "nav.cta": "Créer mon safari",

  /* ---------- Footer ---------- */
  "footer.about":
    "Une structure de safari indépendante basée à Arusha, dirigée par votre guide-chauffeur Emanueli, bilingue français-anglais. Un seul véhicule, un seul guide, un voyage entièrement pensé pour vous.",
  "footer.explore": "Explorer",
  "footer.parks": "Parcs nationaux",
  "footer.contact": "Nous contacter",
  "footer.whatsappBtn": "Écrire sur WhatsApp",
  "footer.rights": "Tous droits réservés.",
  "footer.credit": "Un guide indépendant, fièrement tanzanien.",

  /* ---------- Parks (shared across footer / destinations / tours) ---------- */
  "parks.serengeti": "Serengeti",
  "parks.ngorongoro": "Cratère du Ngorongoro",
  "parks.tarangire": "Tarangire",
  "parks.manyara": "Lac Manyara",
  "parks.kogatende": "Kogatende",

  /* ---------- WhatsApp ---------- */
  "whatsapp.tip": "Écrivez-moi sur WhatsApp",

  /* ---------- Home ---------- */
  "home.hero.eyebrow": "Arusha, Tanzanie",
  "home.hero.title": "Votre aventure, ma passion",
  "home.hero.lede":
    "Guide-chauffeur tanzanien agréé, je vous emmène en petit groupe au cœur du Serengeti, du cratère du Ngorongoro, de Tarangire, du lac Manyara et de Kogatende, à bord de mon propre 4x4 Land Cruiser. Français et anglais courants, itinéraires conçus entièrement autour de vous.",
  "home.hero.ctaPrimary": "Voir les safaris",
  "home.hero.ctaWhatsapp": "Discuter sur WhatsApp",
  "home.hero.stat1": "Ans d'expérience",
  "home.hero.stat2": "Parcs & réserves",
  "home.hero.stat3": "Langues parlées",
  "home.hero.stat4": "Voyages sur mesure",

  "home.trust.t1": "Guide bilingue",
  "home.trust.d1": "Chaque safari conduit en français ou en anglais, selon votre préférence.",
  "home.trust.t2": "4x4 privé",
  "home.trust.d2": "Land Cruiser à toit ouvrant, réservé exclusivement à votre groupe.",
  "home.trust.t3": "Une structure locale",
  "home.trust.d3": "Un guide, une entreprise — pas un centre d'appels anonyme.",
  "home.trust.t4": "Tarifs justes et transparents",
  "home.trust.d4": "Un prix clair par personne, annoncé sans mauvaise surprise.",

  "home.guide.eyebrow": "Votre guide-chauffeur",
  "home.guide.title": "Pas une agence. Juste Emanueli, et la route devant vous.",
  "home.guide.p1":
    "Né et élevé près d'Arusha, j'ai passé ma carrière à lire la brousse : savoir où se déplacent les troupeaux, sentir quand la brume se lève sur le cratère, deviner quelle piste les grands félins emprunteront à l'aube. Chaque itinéraire présenté sur ce site, je l'ai parcouru moi-même, à de nombreuses reprises.",
  "home.guide.p2":
    "Vous ne serez jamais transféré d'un bureau à un autre. De votre accueil à l'aéroport jusqu'à votre dépose, je reste votre guide, votre chauffeur et votre interprète — en français, en anglais et en swahili.",
  "home.guide.cta": "En savoir plus sur Emanueli",

  "home.dest.eyebrow": "Là où nous allons",
  "home.dest.title": "Cinq paysages, un circuit inoubliable",
  "home.dest.lede": "Le circuit classique du nord de la Tanzanie, parcouru par quelqu'un qui l'appelle chez lui.",
  "home.dest.link": "Découvrir →",

  "home.tours.eyebrow": "Itinéraires populaires",
  "home.tours.title": "Quelques façons de commencer",
  "home.tours.lede": "Chaque formule ci-dessous peut être raccourcie, prolongée ou entièrement repensée : ce sont avant tout des points de départ éprouvés.",
  "home.tours.card1.tag": "3 jours",
  "home.tours.card1.title": "Découverte du cratère du Ngorongoro",
  "home.tours.card1.desc": "Les lions arboricoles du lac Manyara, puis une descente complète dans la plus grande caldeira intacte du monde.",
  "home.tours.card2.tag": "6 jours · Le plus demandé",
  "home.tours.card2.title": "Safari signature du nord de la Tanzanie",
  "home.tours.card2.desc": "Tarangire, Serengeti, Ngorongoro et lac Manyara : le circuit classique dans son intégralité.",
  "home.tours.card3.tag": "5 jours · Saisonnier",
  "home.tours.card3.title": "Safari de Kogatende & de la Grande Migration",
  "home.tours.card3.desc": "À la poursuite des traversées de la rivière Mara, dans le nord du Serengeti, de juin à octobre.",
  "home.tours.viewBtn": "Détails",
  "home.tours.allBtn": "Voir tous les safaris",
  "tours.from": "À partir de",

  "home.gallery.eyebrow": "Sur la piste",
  "home.gallery.title": "Instantanés de la route",
  "home.gallery.allBtn": "Voir toute la galerie",

  "home.testi.eyebrow": "Témoignages de voyageurs",
  "home.testi.title": "Ce qu'en disent nos hôtes, une fois la poussière retombée",
  "home.testi.slot": "Votre témoignage trouvera sa place ici — demandez à un voyageur satisfait de partager quelques mots sur son safari avec Emanueli.",
  "home.testi.name": "Nom du voyageur",
  "home.testi.trip": "Safari, mois et année",

  "home.cta.title": "Construisons votre safari ensemble",
  "home.cta.desc": "Communiquez-moi vos dates, votre budget et les rencontres dont vous rêvez : je vous réponds sous 24 heures avec un projet sur mesure.",
  "home.cta.btn1": "Demander un devis gratuit",
  "home.cta.btn2": "WhatsApp Emanueli",

  /* ---------- About ---------- */
  "about.hero.title": "Le guide qui tient le volant",
  "about.hero.lede": "Pas de centre d'appels, pas de chauffeurs interchangeables : un seul guide tanzanien, qui a passé sa vie dans ces parcs et conduit chaque safari en personne.",

  "about.story.eyebrow": "Mon histoire",
  "about.story.title": "De l'ombre du Kilimandjaro aux plaines du Serengeti",
  "about.story.p1":
    "J'ai grandi dans la région d'Arusha, à l'ombre du Kilimandjaro, où voir passer les camions de safari en direction des parcs faisait simplement partie du quotidien. Entré jeune dans le tourisme — d'abord comme porteur, puis comme aide de camp —, je me suis ensuite formé au métier de guide-chauffeur : suivre les traces du gibier, lire le ciel au-dessus du cratère, entretenir un véhicule fiable sur des pistes qui ne pardonnent aucune erreur.",
  "about.story.p2":
    "Après plusieurs années à conduire pour de grands opérateurs, j'ai choisi de me lancer seul, afin que mes clients bénéficient exactement de ce qui m'avait attiré vers ce métier : un guide réellement présent tout au long du voyage, et non un simple nom sur un itinéraire. Aujourd'hui, je dirige Emanueli Tours and Safari comme une structure indépendante à taille humaine — mon propre Land Cruiser, mes propres réservations, mes propres exigences.",
  "about.story.p3":
    "Je parle couramment français et anglais, en plus de mon swahili natal : que votre groupe vienne de Paris, Montréal, Genève ou Bruxelles, aucun interprète ne sera jamais nécessaire entre nous.",

  "about.stats.s1": "Ans d'expérience comme guide-chauffeur",
  "about.stats.s2": "Langues parlées couramment",
  "about.stats.s3": "Places disponibles, en groupe privé ou partagé",
  "about.stats.s4": "Guide du début à la fin — toujours moi",

  "about.values.eyebrow": "Ma façon de travailler",
  "about.values.title": "Les principes qui guident chaque safari",
  "about.values.t1": "Le respect de la faune",
  "about.values.d1": "Des distances responsables, aucune poursuite hors piste, l'observation silencieuse plutôt que la traque bruyante.",
  "about.values.t2": "De petits groupes, uniquement",
  "about.values.d2": "Un seul véhicule, six voyageurs maximum. Ni convoi, ni cohue lors des observations.",
  "about.values.t3": "La ponctualité et l'anticipation",
  "about.values.d3": "Un véhicule entretenu, des itinéraires planifiés et des marges de sécurité intégrées chaque jour.",
  "about.values.t4": "La communauté avant tout",
  "about.values.d4": "Des salaires justes, des fournisseurs locaux et des frais de parc qui financent directement la conservation.",

  "about.vehicle.eyebrow": "Votre véhicule de safari",
  "about.vehicle.title": "Un véritable 4x4, pensé pour la brousse",
  "about.vehicle.lede": "Un Toyota Land Cruiser rigoureusement entretenu, doté d'un toit ouvrant pour une observation debout et sans obstacle — bien loin du minivan reconverti.",
  "about.vehicle.f1": "Toit ouvrant pour une photographie à 360°",
  "about.vehicle.f2": "Ports de recharge USB à chaque siège",
  "about.vehicle.f3": "Glacière garnie d'eau en bouteille à chaque sortie",
  "about.vehicle.f4": "Trousse de premiers secours et communication satellite en zone isolée",

  "about.process.eyebrow": "Planifier ensemble",
  "about.process.title": "Du premier message à l'accueil à l'aéroport",
  "about.process.t1": "Décrivez-moi le safari dont vous rêvez",
  "about.process.d1": "Dates, budget, centres d'intérêt : écrivez-moi sur WhatsApp ou via le formulaire de contact.",
  "about.process.t2": "Je conçois votre itinéraire",
  "about.process.d2": "Un plan jour par jour et un devis clair sous 24 heures, ajusté jusqu'à ce qu'il vous convienne parfaitement.",
  "about.process.t3": "Nous prenons la route",
  "about.process.d3": "Accueil à l'aéroport, puis je reste votre guide, votre chauffeur et votre interprète jusqu'à votre départ.",

  "about.cta.title": "Prêt à parler de votre safari ?",
  "about.cta.desc": "Je réponds personnellement à chaque message, généralement en quelques heures.",
  "about.cta.btn1": "Voir les safaris",
  "about.cta.btn2": "M'écrire directement sur WhatsApp",

  /* ---------- Destinations ---------- */
  "dest.hero.title": "Cinq paysages, un seul circuit du nord",
  "dest.hero.lede": "Chaque safari Emanueli traverse une combinaison de ces cinq lieux. Voici ce qui rend chacun d'eux inoubliable.",

  "dest.bestTime": "Meilleure période :",
  "dest.knownFor": "Réputé pour :",

  "dest.serengeti.eyebrow": "Site du patrimoine mondial de l'UNESCO",
  "dest.serengeti.p1": "Le nom « Serengeti » vient du mot maasaï désignant les « plaines sans fin » — et devant cet horizon, on comprend aussitôt pourquoi tant de voyageurs y voient l'image même de l'Afrique. Plus de trois millions d'herbivores y évoluent, aux côtés de la plus forte densité de prédateurs du continent.",
  "dest.serengeti.p2": "Quel que soit le mois de votre séjour, une partie de la Grande Migration se trouve généralement à portée : mise bas dans les plaines du sud, traversées spectaculaires au nord près de Kogatende, ou simplement une faune résidente exceptionnelle toute l'année dans la région centrale de Seronera.",
  "dest.serengeti.time": "Toute l'année",
  "dest.serengeti.known": "Les grands félins, la migration, les vols en montgolfière",

  "dest.ngorongoro.eyebrow": "Site du patrimoine mondial de l'UNESCO",
  "dest.ngorongoro.p1": "La plus grande caldeira volcanique intacte au monde s'enfonce sur 600 mètres depuis son rebord jusqu'à un fond de cratère abritant environ 25 000 grands mammifères — un enclos naturel si dense qu'une journée entière de safari y semble rarement suffisante.",
  "dest.ngorongoro.p2": "C'est l'un des derniers bastions du rhinocéros noir, gravement menacé, et l'un des rares endroits où l'on peut réellement observer les « Big Five » en une seule descente. Sur le rebord du cratère, les communautés maasaï continuent de faire paître leur bétail comme elles le font depuis des générations.",
  "dest.ngorongoro.time": "Toute l'année, climat plus frais sur le rebord",
  "dest.ngorongoro.known": "Le rhinocéros noir, la densité de la faune, la culture maasaï",

  "dest.tarangire.eyebrow": "Le pays des éléphants",
  "dest.tarangire.p1": "Tarangire abrite la plus grande concentration d'éléphants de Tanzanie en dehors de l'écosystème du Serengeti. En saison sèche, des troupeaux de 200 individus ou plus se rassemblent le long de la rivière Tarangire, entre des baobabs plusieurs fois centenaires.",
  "dest.tarangire.p2": "Plus paisible que le Serengeti ou le Ngorongoro, ce parc constitue une étape de choix en début ou en fin de circuit : une ornithologie remarquable (plus de 550 espèces recensées), quelques lions arboricoles, et certains des paysages les plus photogéniques du nord de la Tanzanie.",
  "dest.tarangire.time": "Juin à octobre (saison sèche)",
  "dest.tarangire.known": "Les éléphants, les baobabs, l'avifaune",

  "dest.manyara.eyebrow": "Un lac du Grand Rift",
  "dest.manyara.p1": "Un mur spectaculaire de l'escarpement du Grand Rift domine un lac alcalin qui, à la bonne saison, se pare de rose sous des milliers de flamants. Entre les deux s'étend une dense forêt-galerie — l'un des rares endroits d'Afrique où les lions grimpent aux arbres.",
  "dest.manyara.p2": "Le parc étant compact, il est aisé d'y combiner forêt, rives du lac et savane ouverte en une seule demi-journée. C'est aussi l'un des rares parcs où marches guidées et sorties en canoë sont proposées.",
  "dest.manyara.time": "Novembre à mai pour les flamants",
  "dest.manyara.known": "Les lions arboricoles, les flamants, l'ornithologie",

  "dest.kogatende.eyebrow": "Le nord du Serengeti",
  "dest.kogatende.p1": "Kogatende ouvre les portes de la rivière Mara, théâtre des scènes les plus spectaculaires de la Grande Migration entre juin et octobre environ : des milliers de gnous et de zèbres se jetant en quelques minutes dans des eaux infestées de crocodiles.",
  "dest.kogatende.p2": "C'est une région reculée — comptez une journée complète de route depuis Arusha — et bien moins fréquentée que le sud du Serengeti, ce qui garantit des points de vue sur les traversées loin de la foule. J'intègre généralement Kogatende aux itinéraires les plus longs, pour que chaque heure de route en vaille pleinement la peine.",
  "dest.kogatende.time": "Juin à octobre (traversées de rivière)",
  "dest.kogatende.known": "Les traversées de la rivière Mara, une observation en toute tranquillité",

  "dest.table.eyebrow": "Conseil pratique",
  "dest.table.title": "Quand visiter chaque parc",
  "dest.table.h1": "Destination",
  "dest.table.h2": "Haute saison",
  "dest.table.h3": "Point fort",

  "dest.extend.eyebrow": "Au-delà du circuit",
  "dest.extend.title": "Prolongez votre voyage",
  "dest.extend.lede": "Complétez votre safari par un avant-goût de la Tanzanie au-delà des parcs — il suffit de le demander lors de la préparation de votre itinéraire.",
  "dest.extend.c1t": "Randonnée d'une journée au Kilimandjaro",
  "dest.extend.c1d": "Un avant-goût du plus haut sommet d'Afrique par la porte de Marangu, sans tentative d'ascension jusqu'au sommet.",
  "dest.extend.c2t": "Montgolfière au-dessus du Serengeti",
  "dest.extend.c2d": "Un lever de soleil sur les plaines, suivi d'un petit-déjeuner en brousse à l'atterrissage.",
  "dest.extend.c3t": "Village maasaï & Zanzibar",
  "dest.extend.c3d": "Une visite culturelle respectueuse, ou quelques jours de détente sur les plages de Zanzibar après la poussière des parcs.",

  "dest.cta.title": "Vous hésitez encore sur les parcs à choisir ?",
  "dest.cta.desc": "Indiquez-moi simplement le nombre de jours dont vous disposez : je vous proposerai la combinaison la plus adaptée.",
  "dest.cta.btn1": "Voir les itinéraires prêts à réserver",
  "dest.cta.btn2": "Demander sur WhatsApp",

  /* ---------- Tours ---------- */
  "tours.hero.title": "Des safaris au prix juste",
  "tours.hero.lede": "Sept itinéraires éprouvés, présentés ci-dessous : chacun peut être raccourci, combiné ou entièrement repensé. Les tarifs s'entendent par personne et diminuent avec la taille du groupe.",

  "tours.filter.all": "Tous les safaris",
  "tours.filter.short": "Courts séjours",
  "tours.filter.classic": "Circuits classiques",
  "tours.filter.migration": "Safaris migration",
  "tours.filter.budget": "Camping économique",

  "tours.groupSize": "De 2 à 6 voyageurs",
  "tours.bookBtn": "Réserver sur WhatsApp",
  "tours.tab.itin": "Itinéraire",
  "tours.tab.price": "Tarifs",
  "tours.table.group": "Taille du groupe",
  "tours.table.pp": "Prix par personne",
  "tours.table.g2": "2 voyageurs",
  "tours.table.g4": "4 voyageurs",
  "tours.table.g6": "6 voyageurs",
  "tours.priceNote": "Tarifs par personne en dollars américains (USD), en occupation double ou partagée. Voir la rubrique « Ce qui est inclus » ci-dessous pour le détail complet.",

  "tours.p1.level": "Lodge milieu de gamme",
  "tours.p1.title": "Taste of Tanzania",
  "tours.p1.desc": "Une introduction brève et inoubliable : les troupeaux d'éléphants de Tarangire, puis les lions arboricoles du lac Manyara — idéale avant ou après un séjour balnéaire.",
  "tours.p1.duration": "2 jours / 1 nuit",
  "tours.p1.day1t": "Arusha → Tarangire",
  "tours.p1.day1d": "Prise en charge le matin à Arusha ou à l'aéroport du Kilimandjaro, puis route vers le parc national de Tarangire pour un safari en après-midi, parmi certains des plus grands troupeaux d'éléphants de Tanzanie et des baobabs séculaires. Nuit dans un lodge à proximité du parc.",
  "tours.p1.day2t": "Lac Manyara → Arusha",
  "tours.p1.day2d": "Transfert matinal vers le parc national du lac Manyara pour un safari à la recherche des lions arboricoles et des flamants roses, puis retour à Arusha en début de soirée.",

  "tours.p2.level": "Lodges milieu de gamme",
  "tours.p2.title": "Ngorongoro Crater Discovery",
  "tours.p2.desc": "Une descente complète dans la plus grande caldeira intacte au monde, associée aux forêts et aux flamants du lac Manyara : l'une des plus fortes densités de faune qui soient.",
  "tours.p2.duration": "3 jours / 2 nuits",
  "tours.p2.day1t": "Arusha → Lac Manyara",
  "tours.p2.day1d": "Prise en charge et route vers Karatu via le parc national du lac Manyara, pour un safari en après-midi. Nuit à proximité des hauts plateaux du Ngorongoro.",
  "tours.p2.day2t": "Cratère du Ngorongoro",
  "tours.p2.day2d": "Descente matinale vers le fond du cratère pour une journée entière au cœur d'une faune dense, avec une réelle chance d'apercevoir le rhinocéros noir. Retour sur le rebord pour la nuit.",
  "tours.p2.day3t": "Culture et retour",
  "tours.p2.day3d": "Arrêt facultatif dans un village maasaï ou au musée des gorges d'Olduvai, puis transfert retour à Arusha.",

  "tours.p3.level": "Lodges milieu de gamme · Le plus demandé",
  "tours.p3.title": "Safari Signature du Nord de la Tanzanie",
  "tours.p3.desc": "Le circuit classique dans son intégralité, et l'itinéraire que je recommande le plus souvent : les éléphants de Tarangire, les plaines infinies du Serengeti, le fond du cratère du Ngorongoro, puis le lac Manyara pour conclure.",
  "tours.p3.duration": "6 jours / 5 nuits",
  "tours.p3.day1t": "Arrivée",
  "tours.p3.day1d": "Accueil à l'aéroport du Kilimandjaro, transfert à Arusha, puis présentation du voyage autour d'un dîner.",
  "tours.p3.day2t": "Parc national de Tarangire",
  "tours.p3.day2d": "Journée entière de safari parmi les troupeaux d'éléphants et un paysage parsemé de baobabs.",
  "tours.p3.day3t": "Serengeti central",
  "tours.p3.day3d": "Route vers le Serengeti central, avec observation de la faune en chemin et un safari en après-midi à l'arrivée.",
  "tours.p3.day4t": "Safaris dans le Serengeti",
  "tours.p3.day4d": "Une journée entière consacrée à la région de Seronera, territoire de prédilection pour les lions, léopards et guépards.",
  "tours.p3.day5t": "Cratère du Ngorongoro",
  "tours.p3.day5d": "Descente vers le fond du cratère pour une journée entière au sein de l'une des populations animales les plus denses d'Afrique.",
  "tours.p3.day6t": "Lac Manyara → départ",
  "tours.p3.day6d": "Safari matinal ou marche guidée au lac Manyara, puis transfert vers l'aéroport du Kilimandjaro pour le départ.",

  "tours.p4.level": "Camps milieu et haut de gamme · Juin–octobre",
  "tours.p4.title": "Safari de Kogatende & de la Grande Migration",
  "tours.p4.desc": "Construit autour des traversées spectaculaires de la rivière Mara, tout au nord du Serengeti : une région reculée, sauvage, bien plus paisible que le circuit sud.",
  "tours.p4.duration": "5 jours / 4 nuits",
  "tours.p4.day1t": "Arusha → Karatu",
  "tours.p4.day1d": "Prise en charge et transfert vers les hauts plateaux du Ngorongoro.",
  "tours.p4.day2t": "Cratère du Ngorongoro",
  "tours.p4.day2d": "Journée entière de safari sur le fond du cratère.",
  "tours.p4.day3t": "Route vers Kogatende",
  "tours.p4.day3d": "Une longue route panoramique vers le nord, à travers le Serengeti central, avec observation de la faune en chemin. Arrivée à Kogatende à temps pour un safari en fin d'après-midi près de la rivière.",
  "tours.p4.day4t": "Traversées de la rivière Mara",
  "tours.p4.day4d": "Une journée entière consacrée aux points de traversée : patience et bon timing peuvent vous offrir l'une des scènes les plus spectaculaires de la nature.",
  "tours.p4.day5t": "Retour à Arusha",
  "tours.p4.day5d": "Route vers le sud à travers le Serengeti central, avec un dernier safari, puis transfert retour à Arusha.",

  "tours.p5.level": "Lodges & camps haut de gamme",
  "tours.p5.title": "Grand Explorateur du Serengeti & de la Migration",
  "tours.p5.desc": "La version approfondie, sans précipitation : deux journées entières à la rivière Mara, tous les parcs classiques, et une montgolfière au lever du soleil en option.",
  "tours.p5.duration": "9 jours / 8 nuits",
  "tours.p5.day1t": "Arrivée",
  "tours.p5.day1d": "Accueil à l'aéroport du Kilimandjaro, transfert à Arusha.",
  "tours.p5.day2t": "Tarangire",
  "tours.p5.day2d": "Journée entière de safari parmi les troupeaux d'éléphants et les baobabs.",
  "tours.p5.day3t": "Serengeti central",
  "tours.p5.day3d": "Route vers le Serengeti central, avec observation de la faune en chemin.",
  "tours.p5.day4t": "Montgolfière & Serengeti",
  "tours.p5.day4d": "Montgolfière au lever du soleil en option (coût supplémentaire, voir la rubrique « suppléments »), suivie d'un safari.",
  "tours.p5.day5t": "Route vers le nord, jusqu'à Kogatende",
  "tours.p5.day5d": "Une route panoramique vers le grand nord, avec observation de la faune en chemin.",
  "tours.p5.day6t": "Traversées de la rivière Mara",
  "tours.p5.day6d": "Une journée entière à la rivière, à la poursuite des moments les plus spectaculaires de la migration.",
  "tours.p5.day7t": "Retour vers le sud",
  "tours.p5.day7d": "Route retour à travers le Serengeti central, en direction des hauts plateaux du Ngorongoro.",
  "tours.p5.day8t": "Cratère du Ngorongoro",
  "tours.p5.day8d": "Descente d'une journée entière vers le fond du cratère.",
  "tours.p5.day9t": "Lac Manyara → départ",
  "tours.p5.day9d": "Safari matinal, puis transfert vers l'aéroport du Kilimandjaro.",

  "tours.p6.level": "Lodges haut de gamme",
  "tours.p6.title": "Circuit Complet du Nord & Aventure Culturelle",
  "tours.p6.desc": "Tous les parcs classiques, complétés par les gorges d'Olduvai, les Hadzabé du lac Eyasi et une visite de village maasaï — pour les voyageurs qui souhaitent découvrir la faune autant que l'histoire humaine qui l'accompagne.",
  "tours.p6.duration": "10 jours / 9 nuits",
  "tours.p6.day1t": "Arrivée",
  "tours.p6.day1d": "Accueil à l'aéroport du Kilimandjaro, transfert à Arusha.",
  "tours.p6.day2t": "Tarangire",
  "tours.p6.day2d": "Journée entière de safari parmi les troupeaux d'éléphants.",
  "tours.p6.day3t": "Lac Manyara",
  "tours.p6.day3d": "Safari, avec option de sortie en canoë ou de marche guidée en supplément.",
  "tours.p6.day4t": "Lac Eyasi",
  "tours.p6.day4d": "Visite matinale des communautés hadzabé et datoga, une occasion rare de découvrir deux des cultures les plus traditionnelles de Tanzanie.",
  "tours.p6.day5t": "Gorges d'Olduvai → Serengeti",
  "tours.p6.day5d": "Arrêt au musée des gorges d'Olduvai, berceau de découvertes majeures sur les origines humaines, puis poursuite vers le Serengeti.",
  "tours.p6.day6t": "Serengeti central",
  "tours.p6.day6d": "Journée entière de safari autour de Seronera.",
  "tours.p6.day7t": "Serengeti, deuxième journée",
  "tours.p6.day7d": "Une deuxième journée dans le parc, ou une excursion facultative vers Kogatende en saison de migration.",
  "tours.p6.day8t": "Ngorongoro & village maasaï",
  "tours.p6.day8d": "Route vers le Ngorongoro, avec une visite de village maasaï en après-midi sur le rebord du cratère.",
  "tours.p6.day9t": "Cratère du Ngorongoro",
  "tours.p6.day9d": "Descente d'une journée entière vers le fond du cratère.",
  "tours.p6.day10t": "Retour à Arusha",
  "tours.p6.day10d": "Transfert à Arusha ou à l'aéroport du Kilimandjaro pour le départ.",

  "tours.p7.level": "Camping mobile sous tente",
  "tours.p7.title": "Safari Camping Aventure",
  "tours.p7.desc": "Les mêmes parcs emblématiques, à un tarif accessible : des nuits sous tente dans des campings publics, où seuls les bruits de la brousse remplacent ceux d'un générateur.",
  "tours.p7.duration": "4 jours / 3 nuits",
  "tours.p7.day1t": "Arusha → Tarangire",
  "tours.p7.day1d": "Prise en charge et route vers Tarangire pour un safari en après-midi. Première nuit en camping à proximité du parc.",
  "tours.p7.day2t": "Serengeti",
  "tours.p7.day2d": "Route vers le Serengeti, avec observation de la faune en chemin. Camping dans le parc ou à ses abords.",
  "tours.p7.day3t": "Safaris dans le Serengeti",
  "tours.p7.day3d": "Une journée entière à explorer les plaines. Deuxième nuit en camping.",
  "tours.p7.day4t": "Ngorongoro → Arusha",
  "tours.p7.day4d": "Safari dans le cratère sur le chemin du retour, puis transfert à Arusha.",

  "tours.incl.eyebrow": "Les conditions, en toute clarté",
  "tours.incl.title": "Ce qui est inclus dans chaque safari",
  "tours.incl.yesTitle": "Inclus",
  "tours.incl.y1": "4x4 Land Cruiser privé, à toit ouvrant",
  "tours.incl.y2": "Emanueli comme guide-chauffeur, francophone et anglophone",
  "tours.incl.y3": "Tous les frais d'entrée de parc et taxes gouvernementales",
  "tours.incl.y4": "Tous les safaris mentionnés dans l'itinéraire",
  "tours.incl.y5": "Hébergement tel que précisé (lodge, camp de tentes ou camping)",
  "tours.incl.y6": "Pension complète pendant toute la durée du safari",
  "tours.incl.y7": "Eau en bouteille à bord pendant les safaris",
  "tours.incl.y8": "Accueil et dépose à l'aéroport (Kilimandjaro ou Arusha)",
  "tours.incl.noTitle": "Non inclus",
  "tours.incl.n1": "Vols internationaux",
  "tours.incl.n2": "Visa pour la Tanzanie",
  "tours.incl.n3": "Assurance voyage, couverture médicale et évacuation",
  "tours.incl.n4": "Pourboires pour le guide et le personnel",
  "tours.incl.n5": "Boissons alcoolisées et boissons premium",
  "tours.incl.n6": "Dépenses personnelles et souvenirs",
  "tours.incl.n7": "Activités facultatives (montgolfière, visites culturelles, randonnées supplémentaires)",

  "tours.addons.eyebrow": "Personnalisez votre safari",
  "tours.addons.title": "Suppléments les plus demandés",
  "tours.addons.lede": "Ajoutez l'un de ces suppléments à n'importe quel itinéraire ci-dessus : il suffit de le mentionner lors de la préparation de votre voyage.",
  "tours.addons.a1": "Montgolfière au lever du soleil sur le Serengeti",
  "tours.addons.a2": "Visite culturelle d'un village maasaï",
  "tours.addons.a3": "Arrêt au musée des gorges d'Olduvai",
  "tours.addons.a4": "Randonnée d'une journée au Kilimandjaro (porte de Marangu)",
  "tours.addons.a5": "Cascades de Materuni & visite d'une plantation de café",
  "tours.addons.a6": "Extension balnéaire à Zanzibar",
  "tours.addons.a7": "Nuit supplémentaire dans un lodge ou un camp",
  "tours.addons.quote": "Sur demande",

  "tours.cta.title": "Vous ne trouvez pas exactement ce qu'il vous faut ?",
  "tours.cta.desc": "Chaque itinéraire présenté ci-dessus est un point de départ. Communiquez-moi vos dates et vos envies : j'en concevrai un entièrement sur mesure.",
  "tours.cta.btn1": "Demander un itinéraire sur mesure",
  "tours.cta.btn2": "WhatsApp Emanueli",

  /* ---------- Gallery ---------- */
  "gal.hero.title": "Instantanés de la route",
  "gal.hero.lede": "Rencontres avec la faune, véhicule qui nous y conduit, et voyageurs qui ont vécu l'aventure : de nouvelles photos sont ajoutées après chaque safari.",
  "gal.video.eyebrow": "À regarder",
  "gal.video.title": "Vidéo de présentation",
  "gal.video.placeholder": "Vidéo de présentation du safari",
  "gal.video.play": "Lire la vidéo",
  "gal.filter.all": "Toutes les photos",
  "gal.filter.wildlife": "Faune",
  "gal.filter.clients": "Voyageurs",
  "gal.filter.vehicle": "Le véhicule",
  "gal.filter.landscapes": "Paysages",
  "gal.more": "De nouvelles photos sont ajoutées après chaque voyage — suivez-nous sur Instagram pour les dernières publications.",
  "gal.cta.title": "Envie de figurer dans la prochaine galerie ?",
  "gal.cta.desc": "Réservez votre safari, et je vous aiderai à l'immortaliser comme il se doit.",
  "gal.cta.btn1": "Voir les safaris",
  "gal.cta.btn2": "WhatsApp Emanueli",

  /* ---------- FAQ ---------- */
  "faq.hero.title": "Questions fréquentes",
  "faq.hero.lede": "Tout ce qu'on me demande avant que mes hôtes ne montent, pour la première fois, dans le Land Cruiser. Vous ne trouvez pas votre réponse ? Écrivez-moi simplement sur WhatsApp.",

  "faq.cat1": "Préparer son voyage",
  "faq.q1": "Quelle est la meilleure période pour partir en safari ?",
  "faq.a1": "Le nord de la Tanzanie se visite toute l'année. La période de juin à octobre (saison sèche) est idéale pour les concentrations d'éléphants de Tarangire et les traversées de la rivière Mara près de Kogatende. Décembre à mars correspond à la période de mise bas de la migration, dans le sud du Serengeti. La « saison verte » (avril–mai) est plus calme, plus abordable, et reste excellente pour l'observation générale de la faune.",
  "faq.q2": "Quand peut-on voir les traversées de la rivière Mara à Kogatende ?",
  "faq.a2": "De juin à octobre environ, sachant que la migration suit les précipitations et non un calendrier : rien n'est jamais garanti à 100 %. Je reste en contact étroit avec d'autres guides sur le terrain afin de planifier nos journées à Kogatende au meilleur moment.",
  "faq.q3": "Pouvez-vous créer un itinéraire sur mesure plutôt que l'une des formules proposées ?",
  "faq.a3": "Toujours. Chaque formule présentée sur ce site n'est qu'un modèle de départ. Communiquez-moi vos dates, votre budget et vos priorités : je vous préparerai un plan jour par jour entièrement sur mesure, sans frais supplémentaires.",
  "faq.q4": "Le safari en Tanzanie convient-il aux familles avec enfants ?",
  "faq.a4": "Oui — je guide régulièrement des familles, et les enfants sont généralement captivés dès la première observation d'éléphants. Je peux adapter la durée et le rythme des trajets aux plus jeunes ; certains lodges imposent toutefois un âge minimum, que je vous indiquerai lors de la préparation du voyage.",

  "faq.cat2": "Pendant le safari",
  "faq.q5": "Combien de personnes partagent le véhicule ?",
  "faq.a5": "Six voyageurs au maximum par Land Cruiser, et je réduis ce nombre chaque fois que possible afin que chacun dispose d'une place côté fenêtre et d'un accès au toit ouvrant. Un véhicule privé et exclusif reste disponible sur demande.",
  "faq.q6": "Quelle est la différence entre un safari en camping et un safari en lodge ?",
  "faq.a6": "Les safaris en lodge ou en camp de tentes de luxe vous logent dans une chambre fixe ou une tente haut de gamme, avec salle de bain privative et service complet. Les safaris en camping utilisent des campings publics, avec sanitaires partagés et équipement mobile — une formule plus aventureuse, et nettement plus abordable. Dans les deux cas, vous bénéficiez exactement des mêmes safaris et du même guidage.",
  "faq.q7": "Quelle condition physique est requise ?",
  "faq.a7": "Aucune condition physique particulière n'est nécessaire pour les safaris en véhicule : vous passez la journée assis, ou debout par le toit ouvrant. Les suppléments facultatifs, comme la randonnée d'une journée au Kilimandjaro ou les marches guidées, demandent davantage d'effort ; je vous expliquerai toujours précisément à quoi vous attendre.",
  "faq.q8": "Que dois-je emporter ?",
  "faq.a8": "Des vêtements de couleurs neutres (évitez le blanc éclatant et le bleu foncé, qui attirent les mouches tsé-tsé), une couche chaude pour les matinées fraîches au cratère, un chapeau, des lunettes de soleil, de la crème solaire, des jumelles, ainsi qu'un appareil photo et une batterie de rechange — la recharge est possible à bord du véhicule. Une liste complète vous sera envoyée dès votre voyage confirmé.",

  "faq.cat3": "Santé & sécurité",
  "faq.q9": "Ai-je besoin d'un visa pour la Tanzanie ?",
  "faq.a9": "La plupart des nationalités doivent obtenir un visa, disponible à l'arrivée ou en ligne à l'avance via le portail officiel e-Visa de Tanzanie. Les conditions évoluant parfois, je vous invite à vérifier auprès de votre ambassade ou du site gouvernemental officiel avant de voyager.",
  "faq.q10": "Quels vaccins sont nécessaires ?",
  "faq.a10": "Un certificat de fièvre jaune est exigé pour les voyageurs en provenance d'un pays à risque de transmission. Un traitement antipaludéen préventif est vivement recommandé dans cette région. Je vous conseille de consulter un centre de vaccinations internationales ou votre médecin traitant quelques semaines avant le départ, pour un avis personnalisé.",
  "faq.q11": "Est-il sûr de voyager en Tanzanie ?",
  "faq.a11": "Le circuit safari du nord de la Tanzanie accueille chaque année des centaines de milliers de voyageurs, et se révèle généralement très sûr. Comme partout, adoptez les précautions de bon sens habituelles en ville ; au sein des parcs, j'applique en permanence des protocoles stricts de distance avec la faune et de sécurité du véhicule.",
  "faq.q12": "Que se passe-t-il en cas d'urgence médicale dans un parc isolé ?",
  "faq.a12": "Le véhicule est équipé d'une trousse de premiers secours et d'un système de communication satellite pour les zones sans réseau mobile, et je reste en contact régulier avec les rangers des parcs et le personnel des lodges. C'est précisément pour cette raison qu'une assurance voyage incluant l'évacuation médicale constitue un préalable indispensable à toute réservation.",

  "faq.cat4": "Argent & réservation",
  "faq.q13": "Comment réserver, et un acompte est-il exigé ?",
  "faq.a13": "Communiquez-moi vos dates et la taille de votre groupe ; je confirme la disponibilité et vous transmets un devis écrit. Un acompte, généralement de 30 %, permet de sécuriser les permis de parc et les réservations de lodge, le solde restant dû avant le début du safari. Les modalités de paiement vous seront communiquées une fois l'itinéraire confirmé.",
  "faq.q14": "Quelle devise emporter, et comment fonctionnent les pourboires ?",
  "faq.a14": "Les dollars américains (billets émis après 2009, sans marque ni déchirure) sont largement acceptés pour les paiements liés aux parcs ; les shillings tanzaniens sont utiles pour les petits achats. Le pourboire reste facultatif mais toujours apprécié — on compte généralement entre 15 et 20 dollars par jour pour votre guide, et un montant similaire pour le personnel des camps et lodges, à ajuster selon votre expérience.",
  "faq.q15": "Parlez-vous français et anglais ?",
  "faq.a15": "Oui, couramment dans les deux langues, en plus de mon swahili natal — votre groupe est donc guidé dans la langue avec laquelle il se sent le plus à l'aise, sans jamais avoir besoin d'un interprète.",
  "faq.q16": "Pouvez-vous organiser les vols ou une extension à Zanzibar ?",
  "faq.a16": "Je peux vous conseiller sur les correspondances de vols intérieurs et organiser une extension balnéaire à Zanzibar à la suite de votre safari, en collaboration avec des partenaires locaux de confiance sur l'île. Il suffit de le mentionner lors de la préparation de votre voyage.",

  "faq.cta.title": "Encore des questions ?",
  "faq.cta.desc": "Écrivez-moi directement : je réponds personnellement, généralement en quelques heures.",
  "faq.cta.btn1": "Formulaire de contact",
  "faq.cta.btn2": "WhatsApp Emanueli",

  /* ---------- Contact ---------- */
  "contact.hero.title": "Planifions votre safari",
  "contact.hero.lede": "Communiquez-moi vos dates, et je vous répondrai personnellement, généralement en quelques heures, avec un projet sur mesure et un devis clair.",

  "contact.card.wa": "WhatsApp",
  "contact.card.waDesc": "La réponse la plus rapide — écrivez-moi dès maintenant",
  "contact.card.email": "E-mail",
  "contact.card.phone": "Téléphone",
  "contact.card.loc": "Basé à",
  "contact.card.locDesc": "Arusha, Tanzanie",

  "contact.form.eyebrow": "Devis gratuit, sans engagement",
  "contact.form.title": "Parlez-moi de votre voyage",
  "contact.form.name": "Nom complet",
  "contact.form.email": "Adresse e-mail",
  "contact.form.dates": "Dates de voyage souhaitées",
  "contact.form.datesPh": "ex. du 12 au 20 juillet 2026",
  "contact.form.travelers": "Nombre de voyageurs",
  "contact.form.message": "Décrivez-moi le safari dont vous rêvez",
  "contact.form.messagePh": "Parcs que vous souhaitez visiter, budget, style d'hébergement, occasion particulière...",
  "contact.form.submit": "Envoyer via WhatsApp",
  "contact.form.status": "Ouverture de WhatsApp avec votre message...",
  "contact.form.altNote": "Vous préférez l'e-mail ? Écrivez à info@emanuelitoursandsafari.com — je réponds tout aussi rapidement.",

  "contact.follow.title": "Suivez-nous",
  "contact.follow.desc": "Voyages récents, observations de faune et coulisses de la route.",

  /* ---------- 404 ---------- */
  "e404.eyebrow": "Hors des sentiers battus",
  "e404.title": "Cette piste ne mène nulle part",
  "e404.lede": "La page que vous recherchez s'est égarée, comme un léopard dans les hautes herbes. Retrouvons ensemble le bon chemin.",
  "e404.btn1": "Retour à l'accueil",
  "e404.btn2": "Voir les safaris",
};
